version: '3.8'
services:
  config-server:
    image: config-server
    build: ./config-server
    ports:
      - "8888:8888"

  service-registry:
    image: service-registry
    build: ./service-registry
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"

  patient-service:
    image: patient-service
    build: ./patient-service
    ports:
      - "8081:8081"

  appointment-service:
    image: appointment-service
    build: ./appointment-service
    ports:
      - "8082:8082"

  inventory-service:
    image: inventory-service
    build: ./inventory-service
    ports:
      - "8083:8083"

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"